### ISSUE TITLE
Does it work for iOS ?

### ISSUE THREAD

**Issue by mandreshope** [Athanax/fullscreen#1]

**Comment by Athanax** [comment]
It's so unfortunate, the package currently only works for Android. IOS coming soon

**Comment by mandreshope** [comment]
Thanks bro

**Comment by crcdng** [comment]
Until the iOS code is implemented, can you implement a stub, some code that compiles and writes a error message to the console? At the moment it crashes already on import which is unfortunate because it makes the plugin unusable.

**Comment by kenngare** [comment]
Am looking into this issue!

**Comment by Athanax** [comment]
Am looking into this issue!

**Comment by Athanax** [comment]
Am looking for a collaboration with an IOS developer to help me solve this.

**Comment by crcdng** [comment]
What I have done on iOS is the follwing:
```
main () {
  WidgetsFlutterBinding.ensureInitialized();
  SystemChrome.setEnabledSystemUIOverlays([]);
 // ..
}
```


This does not have the full functionality of the plugin such as different modes but it does it's job as a quick workaround. 

You could do:

```
import 'dart:io' show Platform;

main () {
  WidgetsFlutterBinding.ensureInitialized();

  if (Platform.isIOS) {
     SystemChrome.setEnabledSystemUIOverlays([]);
     print("INFO: fullscreen plugin currently uses a workaround on iOS");
  } else if (Platform.isAndroid) {
   // your Android code
 }
} 

```

**Comment by Athanax** [comment]
I've updated the plugin to version 1.0.2 which includes iOS support. I'm sorry guys for doing that so late.
https://pub.dev/packages/fullscreen/versions/1.0.2
