### ISSUE TITLE
Downgrade dart sdk minimum version

### ISSUE THREAD

**Issue by ezzabuzaid** [Athanax/fullscreen#4]
Hello.
Thank you for your effort in making this package.

it would be great to have the package working on previous versions of Dart.

so instead of 
```
environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.10.0"
```

would be
```
environment:
  sdk: '>=2.7.0 <3.0.0'
  flutter: ">=1.10.0"
```

the issue with that is I need to update flutter to version 2.x to have this package working.

**Comment by Athanax** [comment]
I really don't understand why you still stuck in that problematic dart version. I've done a bigger project with even the latest version as at now which I started at the start of 2019, I really wanted to support null safety.

**Comment by Athanax** [comment]
You can use the previous versions of the library instead

**Comment by ezzabuzaid** [comment]
Never mind, I had to update to version 2 anyway. 

Thank you.
